---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpa-d840b523
  labels:
    app: jpa-d840b523
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: jpa-d840b523
  template:
    metadata:
      labels:
        app: jpa-d840b523
    spec:
      serviceAccountName: ingress-manager
      containers:
        - name: jpa-d840b523
          image: docker.io/phengbunath/jpa-d840b523:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
